# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: speech_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'speech_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14speech_service.proto\x12\x06speech\"\"\n\x11TranscribeRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\"\"\n\x12TranscribeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1f\n\x0e\x41nalyseRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\"!\n\x0f\x41nalyseResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x1c\n\nAskRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"\x1f\n\x0b\x41skResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\xc0\x01\n\rSpeechService\x12\x43\n\nTranscribe\x12\x19.speech.TranscribeRequest\x1a\x1a.speech.TranscribeResponse\x12:\n\x07\x41nalyse\x12\x16.speech.AnalyseRequest\x1a\x17.speech.AnalyseResponse\x12.\n\x03\x41sk\x12\x12.speech.AskRequest\x1a\x13.speech.AskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'speech_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSCRIBEREQUEST']._serialized_start=32
  _globals['_TRANSCRIBEREQUEST']._serialized_end=66
  _globals['_TRANSCRIBERESPONSE']._serialized_start=68
  _globals['_TRANSCRIBERESPONSE']._serialized_end=102
  _globals['_ANALYSEREQUEST']._serialized_start=104
  _globals['_ANALYSEREQUEST']._serialized_end=135
  _globals['_ANALYSERESPONSE']._serialized_start=137
  _globals['_ANALYSERESPONSE']._serialized_end=170
  _globals['_ASKREQUEST']._serialized_start=172
  _globals['_ASKREQUEST']._serialized_end=200
  _globals['_ASKRESPONSE']._serialized_start=202
  _globals['_ASKRESPONSE']._serialized_end=233
  _globals['_SPEECHSERVICE']._serialized_start=236
  _globals['_SPEECHSERVICE']._serialized_end=428
# @@protoc_insertion_point(module_scope)
