# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings
import speech_service_pb2 as speech__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in speech_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SpeechServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.unary_unary(
                '/speech.SpeechService/Transcribe',
                request_serializer=speech__service__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=speech__service__pb2.TranscribeResponse.FromString,
                _registered_method=True)
        self.Analyse = channel.unary_unary(
                '/speech.SpeechService/Analyse',
                request_serializer=speech__service__pb2.AnalyseRequest.SerializeToString,
                response_deserializer=speech__service__pb2.AnalyseResponse.FromString,
                _registered_method=True)
        self.Ask = channel.unary_unary(
                '/speech.SpeechService/Ask',
                request_serializer=speech__service__pb2.AskRequest.SerializeToString,
                response_deserializer=speech__service__pb2.AskResponse.FromString,
                _registered_method=True)


class SpeechServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Transcribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Analyse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeechServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=speech__service__pb2.TranscribeRequest.FromString,
                    response_serializer=speech__service__pb2.TranscribeResponse.SerializeToString,
            ),
            'Analyse': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyse,
                    request_deserializer=speech__service__pb2.AnalyseRequest.FromString,
                    response_serializer=speech__service__pb2.AnalyseResponse.SerializeToString,
            ),
            'Ask': grpc.unary_unary_rpc_method_handler(
                    servicer.Ask,
                    request_deserializer=speech__service__pb2.AskRequest.FromString,
                    response_serializer=speech__service__pb2.AskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'speech.SpeechService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('speech.SpeechService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpeechService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speech.SpeechService/Transcribe',
            speech__service__pb2.TranscribeRequest.SerializeToString,
            speech__service__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Analyse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speech.SpeechService/Analyse',
            speech__service__pb2.AnalyseRequest.SerializeToString,
            speech__service__pb2.AnalyseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speech.SpeechService/Ask',
            speech__service__pb2.AskRequest.SerializeToString,
            speech__service__pb2.AskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
